name: Build shell-for-ytdlp Executable

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Executable
        run: |
          pyinstaller --onefile --add-data "C:\hostedtoolcache\windows\Python\3.12.6\x64\DLLs\*.dll;DLLs" --hidden-import pyperclip main.py

      - name: List dist directory
        run: dir dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shell-for-ytdlp
          path: dist/shell-for-ytdlp.exe

      - name: Create Draft Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v0.1" dist/shell-for-ytdlp.exe --draft --generate-notes --title "Version v0.1"
