name: Build shell-for-ytdlp Executable

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Set Release Version
        id: vars
        run: echo "RELEASE_VERSION=v0.1" >> $GITHUB_ENV
        # Установите номер версии релиза для использования в процессе релиза

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create Executable
        run: pyinstaller --onefile --add-data "C:\hostedtoolcache\windows\Python\3.12.6\x64\DLLs\*.dll;DLLs" --hidden-import pyperclip --icon "icon.ico" main.py

      - name: List dist directory
        run: dir dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shell-for-ytdlp
          path: dist/shell-for-ytdlp.exe

      - name: Create Draft Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ env.RELEASE_VERSION }}" dist/shell-for-ytdlp.exe --draft --generate-notes --title "Version ${{ env.RELEASE_VERSION }}"
