name: Build shell-for-ytdlp Executable

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create Executable
        run: |
          pyinstaller --onefile --add-data "C:\hostedtoolcache\windows\Python\3.12.6\x64\DLLs\*.dll;DLLs" --hidden-import pyperclip --icon "icon.ico" --name "shell-for-ytdlp" main.py

      - name: List dist directory
        run: |
            tree dist /F /A
            copy main.py dist\main.py
            cd dist
            

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: shell-for-ytdlp
          path: shell-for-ytdlp.exe

      - name: Scan Executable with VirusTotal
        id: virustotal_scan_executable
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_API }}
          files: |
            shell-for-ytdlp.exe

      - name: Scan Source File with VirusTotal
        id: virustotal_scan_source
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_API }}
          files: |
            main.py

      - name: Create Release Notes
        run: |
          cd ..
          echo "Adding VirusTotal report to release notes"
          echo "VirusTotal Report: ${{ steps.virustotal_scan_executable.outputs.analysis }}" >> release_notes.txt
          echo "VirusTotal Report: ${{ steps.virustotal_scan_source.outputs.analysis }}" >> release_notes.txt
          powershell -Command "(Get-Content -Path 'release_notes.txt' -Raw -replace 'VirusTotal Report: ', '' -replace ' ', '' -split '=' | ForEach-Object { '**$($_[0].Trim())**: [View Analysis]($($_[1].Trim()))' }) | Out-File -FilePath 'release_notes.md' -Encoding utf8"

      - name: Create Draft Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v0.1" dist/shell-for-ytdlp.exe --draft --generate-notes --title "Version v0.1" --notes-file release_notes.md
